### ISSUE TITLE
Generating wrong URL when using & in the URL

### ISSUE THREAD

**Issue by mstimvol** [otacke/h5p-kewar-code#25]
We're using the KewAr-Code in Moodle which has version 0.2.1. When I create a KewAr code for a url (e.g. `https://example.tld/index.php?test=1&id=10&abc=def`), I'm getting the following SVG:

![Download](https://user-images.githubusercontent.com/67418257/158327871-94f68d24-4b67-4595-904f-1b490b418956.svg)

When I scan this SVG with my Smartphone (Android) or Tablet (iOS), it "adds" `amp&` to the url. So the url looks like `https://example.tld/index.php?test=1&amp;id=10&amp;abc=def`. But I already selected the correct QR code type in the settings:

![image](https://user-images.githubusercontent.com/67418257/158328255-779d743b-dfe8-4409-bd35-e93f7fb378cc.png)

So is it a bug in the KewAr-Code plugin?

**Comment by otacke** [comment]
Yup, but one I can fix quickly.

**Comment by otacke** [comment]
Fixed by https://github.com/otacke/h5p-kewar-code/commit/e40a3aca5c82a6df5c9bfdb89d831f92da451e3b and released in https://github.com/otacke/h5p-kewar-code/releases/tag/1.1.1

Please note though that I have no control over when the H5P core team might update KewAr Code on the H5P Hub.
