### ISSUE TITLE
Add description field

### ISSUE THREAD

**Issue by otacke** [otacke/h5p-kewar-code#30]
As an author, I want to be able to optionally display textual information along the QR code.

**Comment by MarianCekan** [comment]
Hello, is there a need to interact with already existing data or code? Or is this issue related only to adding some kind of CSS and plain text?

**Comment by otacke** [comment]
@MarianCekan A little coding stuff is involved, but not much.

The `semantics.json` file would need to be amended to facilitate a text input field (with HTML widget and all options) that the author can use to enter his/her text (https://github.com/otacke/h5p-kewar-code/blob/master/semantics.json).

The translation files would then need to be amended accordingly to reflect the new structure of `semantics.json`. https://github.com/otacke/h5p-kewar-code/tree/master/language

And then it would involve to add a new `div` field here https://github.com/otacke/h5p-kewar-code/blob/master/src/scripts/h5p-kewar-code.js#L233-L268 that will show the text that the author provided (if he/she did). May require to put the QR Code and the description into another container `div`.

I'll probably do that later today, but if you'd like to have a shot at it, please let me know.

**Comment by otacke** [comment]
Implemented by https://github.com/otacke/h5p-kewar-code/commit/12f1f7415ef8308a402e0f1a16634245ea8ed280
