### ISSUE TITLE
Kewar URL

### ISSUE THREAD

**Issue by Joanroa** [otacke/h5p-kewar-code#41]
When scanning the QR an "amp" gets added to the URL if there's an "&" symbol, then breaking the link. 

Here's an example: https://joanroa.h5p.com/content/1291951466558401337

**Comment by otacke** [comment]
This was fixed in https://github.com/otacke/h5p-kewar-code/commit/e40a3aca5c82a6df5c9bfdb89d831f92da451e3b in March 2022, but H5P Group is using an outdated version of KewAr Code and a couple of other content types, too.
